"""Hybrid MCTS + LLM trading agent.

Combines MCTS-based gameplay with LLM-powered trade negotiation.
Non-trade actions are delegated to an internal :class:`MCTSAgent`.
Trade proposals and responses are generated by the LLM components
(:class:`TradeGenerator`, :class:`TradeResponder`) and verified by
:class:`MCTSTradeVerifier` before execution via :class:`NegotiationManager`.

Trades are executed as side effects during :meth:`choose_action`; the
returned action index is always a normal gameplay action from MCTSAgent.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

import numpy as np
from numpy.typing import NDArray

from mcts.llm.budget import TokenBudget
from mcts.llm.client import LLMClient, LLMConfig, create_client
from mcts.llm.trade_generator import TradeGenerator
from mcts.llm.trade_responder import TradeResponder
from mcts.negotiation import NegotiationManager, NegotiationRecord
from mcts.trade_verifier import MCTSTradeVerifier

from .base import Agent
from .mcts_agent import MCTSAgent

if TYPE_CHECKING:
    from monopoly_engine.game import MonopolyGame

logger = logging.getLogger(__name__)


@dataclass
class HybridAgentConfig:
    """Configuration for the hybrid MCTS + LLM agent."""

    # LLM settings
    llm_config: LLMConfig = field(default_factory=LLMConfig)

    # MCTS gameplay
    mcts_simulations: int = 200
    mcts_temperature: float = 0.0

    # MCTS trade verification
    trade_eval_simulations: int = 50
    trade_acceptance_threshold: float = 0.02

    # Negotiation settings
    max_negotiation_rounds: int = 3
    max_trades_per_game: int = 10

    # Trade timing (see C3 for full implementation)
    trade_check_interval: int = 5

    # Fast-path thresholds
    fast_accept_threshold: float = 0.10

    # Budget
    token_budget: TokenBudget = field(default_factory=TokenBudget)


class HybridAgent(Agent):
    """Combined MCTS + LLM trading agent.

    Decision flow for each :meth:`choose_action` call:

    1. Check :class:`NegotiationManager` for pending negotiations
       awaiting this player's response.
    2. If a pending negotiation exists: evaluate via
       :class:`MCTSTradeVerifier` + :class:`TradeResponder`, then
       accept / reject / counter-propose via NegotiationManager.
    3. If no pending negotiation and trade timing triggers: generate
       a proposal via :class:`TradeGenerator`, verify with MCTS,
       and start a negotiation if approved.
    4. Delegate normal gameplay (roll, buy, build, end turn) to the
       internal :class:`MCTSAgent`.

    Trade actions are executed directly on the game via
    NegotiationManager.  The returned action index is always a normal
    gameplay action from MCTSAgent.
    """

    def __init__(
        self,
        player_id: int,
        config: HybridAgentConfig | None = None,
        negotiation_manager: NegotiationManager | None = None,
        llm_client: LLMClient | None = None,
    ) -> None:
        """Initialize the hybrid agent.

        Args:
            player_id: The player this agent controls.
            config: Agent configuration.  Uses defaults if ``None``.
            negotiation_manager: Shared negotiation manager.  If ``None``,
                creates one.  **Must** be shared across all HybridAgent
                instances in the same game.
            llm_client: Optional pre-built LLM client.  If ``None``,
                creates one from ``config.llm_config``.
        """
        super().__init__(player_id=player_id, name=f"HybridAgent(p{player_id})")

        self._config = config or HybridAgentConfig()

        # MCTS agent for normal gameplay
        self._mcts_agent = MCTSAgent(
            player_id=player_id,
            num_simulations=self._config.mcts_simulations,
            temperature=self._config.mcts_temperature,
        )

        # Trade verifier
        self._verifier = MCTSTradeVerifier(
            simulations_per_eval=self._config.trade_eval_simulations,
            acceptance_threshold=self._config.trade_acceptance_threshold,
        )

        # LLM components
        if llm_client is not None:
            self._llm_client = llm_client
            self._owns_client = False
        else:
            self._llm_client = create_client(self._config.llm_config)
            self._owns_client = True

        self._generator = TradeGenerator(self._llm_client)
        self._responder = TradeResponder(
            self._llm_client,
            mcts_value_threshold=self._config.fast_accept_threshold,
        )

        # Negotiation tracking
        self._negotiation_mgr = negotiation_manager or NegotiationManager(
            max_rounds=self._config.max_negotiation_rounds,
        )

        # Per-game counters
        self._budget = self._config.token_budget
        self._trades_proposed: int = 0
        self._last_trade_turn: int = -999

    def choose_action(
        self,
        observation: dict[str, Any],
        action_mask: NDArray[np.bool_],
        game: MonopolyGame,
    ) -> int:
        """Select an action.

        Handles trade logic as a side effect, then delegates to MCTSAgent
        for the normal gameplay action.
        """
        self._handle_trade_phase(game)
        return self._mcts_agent.choose_action(observation, action_mask, game)

    # ------------------------------------------------------------------
    # Trade orchestration
    # ------------------------------------------------------------------

    def _handle_trade_phase(self, game: MonopolyGame) -> None:
        """Respond to pending negotiations or propose new trades."""
        # 1. Respond to pending negotiations first
        pending = self._negotiation_mgr.get_pending_for_player(self.player_id)
        if pending:
            self._respond_to_negotiation(game, pending[0])
            return

        # 2. Maybe propose a new trade
        if self._should_attempt_trade(game):
            self._generate_and_verify_trade(game)

    def _should_attempt_trade(self, game: MonopolyGame) -> bool:
        """Check if trade timing strategy says we should try trading.

        Stub implementation for C2; full heuristics added in C3.
        """
        # Budget checks
        if not self._budget.budget_remaining:
            return False
        if self._trades_proposed >= self._config.max_trades_per_game:
            return False

        # Basic interval check
        turn = game.state.turn_number
        if turn - self._last_trade_turn < self._config.trade_check_interval:
            return False

        return True

    def _generate_and_verify_trade(self, game: MonopolyGame) -> bool:
        """Generate a trade via LLM, verify via MCTS, execute if approved.

        Returns:
            True if a trade was proposed, False otherwise.
        """
        # Generate proposal via LLM
        proposal = self._generator.generate_proposal(game, self.player_id)
        self._budget.record_usage()

        if proposal is None:
            return False

        # Convert ProposeTrade to TradeOfferData for MCTS evaluation
        from monopoly_engine.types import TradeOfferData

        trade_data: TradeOfferData = {
            "from_player": self.player_id,
            "to_player": proposal.to_player,
            "give_properties": proposal.give_properties,
            "give_money": proposal.give_money,
            "want_properties": proposal.want_properties,
            "want_money": proposal.want_money,
        }

        # Verify with MCTS
        evaluation = self._verifier.evaluate_trade(
            game, self.player_id, trade_data,
        )

        if not evaluation.recommended:
            logger.info(
                "MCTS rejected LLM proposal (delta=%.3f < threshold=%.3f)",
                evaluation.value_delta,
                self._config.trade_acceptance_threshold,
            )
            return False

        # Execute via NegotiationManager
        try:
            self._negotiation_mgr.start_negotiation(
                game,
                from_player=self.player_id,
                to_player=proposal.to_player,
                give_properties=proposal.give_properties,
                give_money=proposal.give_money,
                want_properties=proposal.want_properties,
                want_money=proposal.want_money,
            )
        except ValueError as exc:
            logger.warning("Trade proposal failed engine validation: %s", exc)
            return False

        self._trades_proposed += 1
        self._last_trade_turn = game.state.turn_number
        logger.info(
            "Proposed trade to Player %d (MCTS delta=%.3f)",
            proposal.to_player,
            evaluation.value_delta,
        )
        return True

    def _respond_to_negotiation(
        self,
        game: MonopolyGame,
        negotiation: NegotiationRecord,
    ) -> None:
        """Respond to an incoming trade negotiation."""
        if not negotiation.history:
            self._negotiation_mgr.reject(
                game, negotiation.negotiation_id, self.player_id,
            )
            return

        trade = negotiation.history[-1]

        # Evaluate with MCTS
        evaluation = self._verifier.evaluate_trade(
            game, self.player_id, trade,
        )

        # Ask LLM (with MCTS values for fast path)
        decision = self._responder.respond_to_trade(
            game,
            self.player_id,
            trade,
            mcts_value_before=evaluation.value_before,
            mcts_value_after=evaluation.value_after,
        )
        self._budget.record_usage()

        action = decision.get("decision", "reject")

        if action == "accept":
            self._negotiation_mgr.accept(
                game, negotiation.negotiation_id, self.player_id,
            )
            logger.info(
                "Accepted trade (MCTS delta=%.3f): %s",
                evaluation.value_delta,
                decision.get("reasoning", ""),
            )

        elif action == "counter" and "counter_proposal" in decision:
            cp = decision["counter_proposal"]
            if cp:
                self._negotiation_mgr.counter_propose(
                    game,
                    negotiation.negotiation_id,
                    self.player_id,
                    give_properties=cp.get("give_properties", []),
                    give_money=cp.get("give_money", 0),
                    want_properties=cp.get("want_properties", []),
                    want_money=cp.get("want_money", 0),
                )
                logger.info("Counter-proposed: %s", decision.get("reasoning", ""))
            else:
                # Empty counter → reject
                self._negotiation_mgr.reject(
                    game, negotiation.negotiation_id, self.player_id,
                )

        else:
            self._negotiation_mgr.reject(
                game, negotiation.negotiation_id, self.player_id,
            )
            logger.info(
                "Rejected trade (MCTS delta=%.3f): %s",
                evaluation.value_delta,
                decision.get("reasoning", ""),
            )

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def reset(self) -> None:
        """Reset per-game state."""
        self._mcts_agent.reset()
        self._budget.reset()
        self._negotiation_mgr.reset()
        self._trades_proposed = 0
        self._last_trade_turn = -999

    @property
    def negotiation_manager(self) -> NegotiationManager:
        """The shared NegotiationManager instance."""
        return self._negotiation_mgr

    @property
    def trades_proposed(self) -> int:
        """Number of trades proposed this game."""
        return self._trades_proposed

    def close(self) -> None:
        """Clean up resources."""
        if self._owns_client:
            self._llm_client.close()
