import { test, expect } from '@playwright/test';
import states from './fixtures/foundation.json' with { type: 'json' };

// Public API snapshots generated by the real foundation engine. The transport is
// scripted here; Python API parity tests separately exercise command execution.
for (const scenario of [
  { before: 'jail', after: 'paid', button: /Pay 50 dollar fine/, action: 'pay_jail_fine' },
  {
    before: 'debt',
    after: 'rescued',
    button: /Mortgage Property · property 39/,
    action: 'mortgage_property',
  },
  { before: 'purchase', after: 'passed', button: /Pass on buying/, action: 'pass_buy' },
] as const) {
  test(`foundation ${scenario.before} decision survives reconnect`, async ({ page }) => {
    const commands: Record<string, unknown>[] = [];
    let state = states[scenario.before];
    await page.addInitScript(() => {
      localStorage.setItem(
        'monopoly-session',
        JSON.stringify({
          state: { sessionId: 'foundation-browser', displayName: 'Player 1' },
          version: 0,
        })
      );
    });
    await page.routeWebSocket('**/ws/games/**', (ws) => {
      ws.send(JSON.stringify({ type: 'identity', data: { player_id: 0 } }));
      ws.send(JSON.stringify({ type: 'state_update', data: state }));
      ws.onMessage((raw) => {
        const message = JSON.parse(String(raw));
        if (message.type !== 'action') return;
        commands.push(message.data);
        state = states[scenario.after];
        ws.send(JSON.stringify({ type: 'action_result', data: { success: true } }));
        ws.send(JSON.stringify({ type: 'state_update', data: state }));
      });
    });
    await page.goto('/game/foundation-browser');
    await expect(page.getByText(/Rules: foundation-v1/)).toBeVisible();
    await expect(page.getByRole('button', { name: scenario.button })).toBeEnabled();
    await page.reload();
    await expect(page.getByRole('button', { name: scenario.button })).toBeEnabled();
    await page.getByRole('button', { name: scenario.button }).click();
    await expect.poll(() => commands.length).toBe(1);
    expect(commands[0].action_type).toBe(scenario.action);
    if (scenario.before === 'debt') {
      expect(commands[0].property_position).toBe(39);
      await expect(page.getByRole('region', { name: 'Debt resolution' })).toHaveCount(0);
    }
    if (scenario.before === 'purchase') {
      await expect(page.getByRole('button', { name: /roll/i })).toBeEnabled();
      await expect(page.getByRole('button', { name: /end.*turn/i })).toHaveCount(0);
    }
  });
}
